# Generated by Django 6.0.3 on 2026-04-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Garbage', 'Garbage (குப்பை)'), ('Road', 'Road Damage (சாலை சேதம்)'), ('Water', 'Water Problem (தண்ணீர் பிரச்சனை)'), ('Street_Light', 'Street Light (தெரு விளக்கு)'), ('Others', 'Others (மற்றவை)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending (நிலுவையில்)'), ('In Progress', 'In Progress (செயல்பாட்டில்)'), ('Resolved', 'Resolved (தீர்வு காணப்பட்டது)')], default='Pending', max_length=20),
        ),
    ]
