# Generated by Django 6.0.3 on 2026-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_category_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location_address',
            field=models.CharField(blank=True, help_text='Street name or landmark', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
    ]
